version = 1

[[annotations]]
path = [
  "loki/**/tests/**/*.F90",
  "loki/**/tests/**/*.f90",
  "loki/**/tests/**/*.h",
  "example/**/*.F90",
  "example/**/*.f90",
  "example/**/*.h",
]
precedence = "closest"
SPDX-FileCopyrightText = "2018 European Centre for Medium-Range Weather Forecasts (ECMWF)"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "In applying this licence, ECMWF does not waive the privileges and immunities granted to it by virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction."
