MODULE TEST_SC_POTENTIAL_6_MOD
CONTAINS
  SUBROUTINE TEST_SC_POTENTIAL_6(KIDIA, KFIDIA, ZTP1, KLON, KLEV)

    INTEGER, INTENT(IN) :: KIDIA, KFIDIA, KLON, KLEV
    REAL, INTENT(INOUT) :: ZTP1(KLON, KLEV), Z(KLEV)
    REAL :: SCALAR_TMP, TMP(KLON)
    INTEGER :: JL, JK, JO, JN, JM

    DO JK=1,KLEV
      DO JL=KIDIA,KFIDIA
        Z(JK) = 0.0
        ZTP1(JL, JK) = ZTP1(JL-1, JK)
        ZTP1(JL, JK) = ZTP1(JL+1, JK)
        ZTP1(JL+1, JK) = ZTP1(JL, JK)
      END DO
    END DO

  END SUBROUTINE TEST_SC_POTENTIAL_6
END MODULE TEST_SC_POTENTIAL_6_MOD
