from pathlib import Path
import contextlib
import os
import io

from fparser.two.parser import ParserFactory
import fparser.two.Fortran2003 as f2003

from loki import (
    SourceFile, Module, Subroutine, fgen, OFP, OMNI, compile_and_load, FindNodes, CallStatement,
    Scope)
from loki.build import Builder, Lib, Obj
from loki.frontend.fparser import parse_fparser_ast
from loki.tools import gettempdir, filehash


__all__ = ['generate_identity', 'jit_compile', 'jit_compile_lib', 'clean_test',
           'clean_preprocessing', 'stdchannel_redirected', 'stdchannel_is_captured',
           'parse_expression']


def generate_identity(refpath, routinename, modulename=None, frontend=OFP):
    """
    Generate the "identity" of a single subroutine with a frontend-specific suffix.
    """
    testname = refpath.parent/('%s_%s_%s.f90' % (refpath.stem, routinename, frontend))
    source = SourceFile.from_file(refpath, frontend=frontend)

    if modulename:
        module = [m for m in source.modules if m.name == modulename][0]
        module.name += '_%s_%s' % (routinename, frontend)
        for routine in source.all_subroutines:
            routine.name += '_%s' % frontend
            for call in FindNodes(CallStatement).visit(routine.body):
                call.name += '_%s' % frontend
        source.write(path=testname, source=fgen(module))
    else:
        routine = [r for r in source.subroutines if r.name == routinename][0]
        routine.name += '_%s' % frontend
        source.write(path=testname, source=fgen(routine))

    pymod = compile_and_load(testname, cwd=str(refpath.parent), use_f90wrap=True)

    if modulename:
        # modname = '_'.join(s.capitalize() for s in refpath.stem.split('_'))
        return getattr(pymod, testname.stem)
    return pymod


def jit_compile(source, filepath=None, objname=None):
    """
    Generate, Just-in-Time compile and load a given item (`Module` or
    `Subroutine`) for interactive execution.
    """
    if isinstance(source, SourceFile):
        filepath = source.filepath if filepath is None else Path(filepath)
        source.write(path=filepath)
    else:
        source = fgen(source)
        if filepath is None:
            filepath = gettempdir()/filehash(source, prefix='', suffix='.f90')
        else:
            filepath = Path(filepath)
        SourceFile(filepath).write(source=source)

    pymod = compile_and_load(filepath, cwd=str(filepath.parent), use_f90wrap=True)

    if objname:
        return getattr(pymod, objname)
    return pymod


def jit_compile_lib(sources, path, name, wrap=None, builder=None):
    """
    Generate, just-in-time compile and load a set of items into a
    library and import dynamically into the Python runtime.

    :param source: Source items or filepath to compile and add to lib
    :param path: Basepath for on-the-fly creation of source files
    :param name: Name of created lib
    :param wrap: Optional list of files names to pass to f90wrap.
                 Defaults to list of source files.
    :param builder: Builder object to use for lib compilation and linking
    """
    builder = builder or Builder(source_dirs=path, build_dir=path)
    sourcefiles = []

    for source in sources:
        if isinstance(source, (str, Path)):
            sourcefiles.append(source)

        if isinstance(source, SourceFile):
            filepath = source.path or path/'{}.f90'.format(source.name)
            source.write(path=filepath)
            sourcefiles.append(source.path)

        elif isinstance(source, Module):
            filepath = path/'{}.f90'.format(source.name)
            source = SourceFile(filepath, modules=[source])
            source.write(path=filepath)
            sourcefiles.append(source.path)

        elif isinstance(source, Subroutine):
            filepath = path/'{}.f90'.format(source.name)
            source = SourceFile(filepath, routines=[source])
            source.write(path=filepath)
            sourcefiles.append(source.path)

    objects = [Obj(source_path=s) for s in sourcefiles]
    lib = Lib(name=name, objs=objects, shared=False)
    lib.build(builder=builder)
    wrap = wrap or sourcefiles
    return lib.wrap(modname=name, sources=wrap, builder=builder)


def clean_test(filepath):
    """
    Clean test directory based on JIT'ed source file.
    """
    file_list = [filepath.with_suffix('.f90'), filepath.with_suffix('.o'),
                 filepath.with_suffix('.py'), filepath.parent/'f90wrap_toplevel.f90']
    for f in file_list:
        if f.exists():
            f.unlink()
    for sofile in filepath.parent.glob('_%s.*.so' % filepath.stem):
        sofile.unlink()
    f90wrap_path = filepath.parent/'f90wrap_{}'.format(filepath.name)
    if f90wrap_path.exists():
        f90wrap_path.unlink()


def clean_preprocessing(filepath, frontend):
    """
    Clean test directory from files generated by preprocessing in the frontends.
    """
    def unlink_if_exists(filepath):
        """
        Removes the file if it exists (In Python 3.8+ this can also be achieved
        with the `missing_ok` parameter.
        """
        if filepath.exists():
            filepath.unlink()

    suffix = filepath.suffix
    unlink_if_exists(filepath.with_suffix('.%s%s' % (frontend, suffix)))
    unlink_if_exists(filepath.with_suffix('.%s.info' % frontend))
    if frontend == OFP:
        unlink_if_exists(filepath.with_suffix('.%s%s.ofpast' % (frontend, suffix)))
    if frontend == OMNI:
        unlink_if_exists(filepath.with_suffix('.%s.xml' % frontend))


@contextlib.contextmanager
def stdchannel_redirected(stdchannel, dest_filename):
    """
    A context manager to temporarily redirect stdout or stderr

    e.g.:

    ```
    with stdchannel_redirected(sys.stderr, os.devnull):
        if compiler.has_function('clock_gettime', libraries=['rt']):
            libraries.append('rt')
    ```

    Source: https://stackoverflow.com/a/17753573

    Note, that this only works when pytest is invoked with '--show-capture' (or '-s').
    This can be checked using `stdchannel_is_captured(capsys)`.
    Additionally, capturing of sys.stdout/sys.stderr needs to be disabled explicitly,
    i.e., use the fixture `capsys` and wrap the above:

    ```
    with capsys.disabled():
        with stdchannel_redirected(sys.stdout, 'stdout.log'):
            function()
    ```
    """

    def try_dup(fd):
        try:
            oldfd = os.dup(fd.fileno())
        except io.UnsupportedOperation:
            oldfd = None
        return oldfd

    def try_dup2(fd, fd2, fd_fileno=True):
        try:
            if fd_fileno:
                os.dup2(fd.fileno(), fd2.fileno())
            else:
                os.dup2(fd, fd2.fileno())
        except io.UnsupportedOperation:
            pass

    oldstdchannel, dest_file = None, None
    try:
        oldstdchannel = try_dup(stdchannel)
        dest_file = open(dest_filename, 'w')
        try_dup2(dest_file, stdchannel)

        yield
    finally:
        if oldstdchannel is not None:
            try_dup2(oldstdchannel, stdchannel, fd_fileno=False)
        if dest_file is not None:
            dest_file.close()


def stdchannel_is_captured(capsys):
    """
    Utility function to verify if pytest captures stdout/stderr.

    This hinders redirecting stdout/stderr for f2py/f90wrap functions.

    :param capsys: the capsys fixture of the test.
    :returns: True if pytest captures output, otherwise False.
    """

    capturemanager = capsys.request.config.pluginmanager.getplugin("capturemanager")
    return capturemanager._global_capturing.out is not None


def parse_expression(source, scope=None):
    """
    Parse an expression string into an expression tree.
    """
    scope_ = scope if scope is not None else Scope()

    # Unfortunately, this is necessary if fparser has not been invoked before
    # to instantiate the class hierarchy. Not sure if there is any way of
    # testing if that has already been done.
    _ = ParserFactory().create('f2008')

    ir = parse_fparser_ast(f2003.Primary(source), source, scope=scope_)
    if scope is None:
        return ir, scope_
    return ir
