MODULE GEOMETRY_MOD
IMPLICIT NONE

TYPE DIMENSION_TYPE
  INTEGER :: NGPBLKS
  INTEGER :: NPROMA
END TYPE DIMENSION_TYPE

TYPE GEM_TYPE
  INTEGER :: NGPTOT
END TYPE GEM_TYPE

TYPE GEOMETRY_TYPE
  TYPE(DIMENSION_TYPE) :: YRDIM
  TYPE(GEM_TYPE) :: YRGEM
END TYPE GEOMETRY_TYPE

END MODULE GEOMETRY_MOD
