MODULE KERNEL_GEOM_MOD
  USE GEOMETRY_MOD, ONLY: GEOMETRY_TYPE
  IMPLICIT NONE
CONTAINS

  SUBROUTINE kernel_geom(ydgeometry, flag1)
    TYPE(GEOMETRY_TYPE), INTENT(IN) :: ydgeometry
    LOGICAL, INTENT(IN) :: flag1

  END SUBROUTINE kernel_geom

END MODULE KERNEL_GEOM_MOD
