INTERFACE
SUBROUTINE KERNEL_A1(B, C, FLAG1, FLAG2)
REAL, INTENT(INOUT) :: B(:,:)
REAL, INTENT(INOUT) :: C(:,:)
LOGICAL, OPTIONAL, INTENT(IN) :: FLAG1
LOGICAL, OPTIONAL, INTENT(IN) :: FLAG2
END SUBROUTINE KERNEL_A1
END INTERFACE
