#!/usr/bin/env python

# (C) Copyright 2018- ECMWF.
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

"""
An offline script to generate the complex control-flow patterns of the
EC-physics drivers.
"""

from pathlib import Path
import click

from loki import config as loki_config, Sourcefile, Scheduler


@click.group()
def cli():
    pass


@cli.command()
@click.option('--source', '-s', '--path', type=click.Path(), default=Path.cwd(),
              help='Path to search for initial input sources.')
@click.option('--build', '-b', '--out', type=click.Path(), default=None,
              help='Path to build directory for source generation.')
@click.option('--log-level', '-l', default='info', envvar='LOKI_LOGGING',
              type=click.Choice(['debug', 'detail', 'perf', 'info', 'warning', 'error']),
              help='Log level to output during processing')
def inline(source, build, log_level):
    """
    Inlines EC_PHYS and CALLPAR into EC_PHYS_DRV to expose the parallel loop.
    """
    loki_config['log-level'] = log_level

    source = Path(source)

    config =  {
        'default': {
            'mode': 'idem',
            'role': 'kernel',
            'expand': False,
            'strict': True,
            'enable_imports': False,
        },
        'routines' : {
            'ec_phys_drv' : {'role': 'driver',},
            'ec_phys' : {},
            'callpar' : {},
        }
    }

    # Parse and enrich the needed source files
    scheduler = Scheduler(config=config, paths=source, output_dir=build)

    ec_phys_fc = scheduler['#ec_phys_drv'].ir

    # Change subroutine name
    ec_phys_fc.name = 'EC_PHYS_FC'

    # Replace the docstring to mark routine as auto-generated
    ec_phys_fc.docstring = """
    !**** *EC_PHYS_FC* - Standalone physics forecast-only driver

    !     Purpose.
    !     --------
    !           An automatically generated driver routine that exposes
    !           parallel regions alongside the physics control flow for
    !           using different parallelisation methods, including GPU offload.

    !     **  THIS SUBROUTINE HAS BEEN AUTO-GENERATED BY LOKI  **

    !     It is a combination of EC_PHYS_DRV, EC_PHYS and CALLPAR and be re-derived from them.

"""

    # And write the generated subroutine to file
    Sourcefile(path=build/'ec_phys_fc.F90', ir=(ec_phys_fc,)).write()
